### ISSUE TITLE
No code?

### ISSUE THREAD

**Issue by mirkoRainer** [mattfreeman-london/Pathfinder2e-Wild_Shape#1]
I don’t immediately see where your code is. It also looks like your folders may be cluttered with non-needed items. The .zip file specifically looks unneeded.

**Comment by mirkoRainer** [comment]
It appears your code lives under `jasmine-standalone-3.5.0/`. 
Is there a reason it’s nested?
It would be easier to find if your main folders/files are at top level and you could remove the unneeded folders/files (the _Mac... doesn’t need to be there)

**Comment by mirkoRainer** [comment]
Why is it named `training.js`?
Would it make more sense to call it `proficiency.js`, since it's a reflection of the PC's proficiency? This is the nomenclature used in the rulebook so it seems more appropriate.
Also, it only seems to go up to Expert?

**Comment by mattfreeman-london** [comment]
Thanks for your input, it's fantastic. I'm still kind of new, so this all makes a lot of sense. 
I've made the changes as you've listed.
Proficiency only goes up to Expert as Pathfinder 2e Druids only go up to that point, never any higher.

**Comment by mirkoRainer** [comment]
> Proficiency only goes up to Expert as Pathfinder 2e Druids only go up to that point, never any higher.

This makes sense for this tool, but have you thought about expanding this into other PF2e tools? If so, if you're able to write the logic around Proficiencies now, you would be able to re-use that code on a different project without having to rewrite things. 
Just something to think about when you're writing: How can I write this to be reusable by myself or someone else? The whole "re-inventing the wheel" trope is pretty common in software development.
